import { User } from '../interfaces/user.interface';

export const USUARIOS: User[] = [
  {
    id: 1,
    first_name: 'María del Carmen',
    last_name: 'Herrera Villanueva',
    username: 'mariadelcarmen.herrera',
    email: 'mariadelcarmen.herreravillanueva@peticiones.online',
    image: './assets/flat-ion-alumn.jpeg',
  },
  {
    id: 2,
    first_name: 'Marisol',
    last_name: 'Venegas Jurado',
    username: 'marisol.venegas',
    email: 'marisol.venegasjurado@peticiones.online',
    image: './assets/flat-ion-alumn.jpeg',
  },
  {
    id: 45,
    first_name: 'Marisol',
    last_name: 'Venegas Jurado',
    username: 'marisol.venegas',
    email: 'marisol.venegasjurado@peticiones.online',
    image: './assets/flat-ion-alumn.jpeg',
  },
  {
    id: 46,
    first_name: 'Marisol',
    last_name: 'Venegas Jurado',
    username: 'marisol.venegas',
    email: 'marisol.venegasjurado@peticiones.online',
    image: './assets/flat-ion-alumn.jpeg',
  },
  {
    id: 47,
    first_name: 'Marisol',
    last_name: 'Venegas Jurado',
    username: 'marisol.venegas',
    email: 'marisol.venegasjurado@peticiones.online',
    image: './assets/flat-ion-alumn.jpeg',
  },
  {
    id: 3,
    first_name: 'Marisol',
    last_name: 'Venegas Jurado',
    username: 'marisol.venegas',
    email: 'marisol.venegasjurado@peticiones.online',
    image: './assets/flat-ion-alumn.jpeg',
  },
  {
    id: 5,
    first_name: 'Marisol',
    last_name: 'Venegas Jurado',
    username: 'marisol.venegas',
    email: 'marisol.venegasjurado@peticiones.online',
    image: './assets/flat-ion-alumn.jpeg',
  },
];
